from __future__ import annotations

from datetime import UTC, datetime

import gpxpy.gpx


def build_gpx(
    *,
    name: str,
    coordinates: list[list[float]],
    waypoints: list[list[float]] | None = None,
    created_at: datetime | None = None,
) -> str:
    gpx = gpxpy.gpx.GPX()
    gpx.creator = "RunCanvas"
    gpx.version = "1.1"
    gpx.name = name
    gpx.description = "GPS art running course generated by RunCanvas"
    gpx.time = created_at or datetime.now(UTC)
    track = gpxpy.gpx.GPXTrack(name=name)
    segment = gpxpy.gpx.GPXTrackSegment()
    track.segments.append(segment)
    gpx.tracks.append(track)
    for coordinate in coordinates:
        elevation = float(coordinate[2]) if len(coordinate) >= 3 else None
        segment.points.append(
            gpxpy.gpx.GPXTrackPoint(
                latitude=float(coordinate[1]),
                longitude=float(coordinate[0]),
                elevation=elevation,
            )
        )
    for index, coordinate in enumerate(waypoints or [], start=1):
        gpx.waypoints.append(
            gpxpy.gpx.GPXWaypoint(
                latitude=float(coordinate[1]),
                longitude=float(coordinate[0]),
                name=f"Waypoint {index}",
            )
        )
    return gpx.to_xml(version="1.1")
